version: "3.9"
services: 
  github-viewer:
    build: ./
    container_name: github-viewer
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    environment:      
      - PORT=${PORT}
    working_dir: /app
    command: sh -c "cd /app; rm -rf node_modules; npm install --force; npm run server"
